### ISSUE TITLE
我用 Hackintool 定制了 USB 端口，但是并不生效

### ISSUE THREAD

**Issue by huijiewei** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#1]
能帮我看下什么问题么

https://i.loli.net/2020/05/09/OXy38wKeD6zUau2.png

**Comment by imEgo** [comment]
具体哪里没生效呢，图片里大部分HS和SS的接口都已经屏蔽掉了

**Comment by huijiewei** [comment]
> 具体哪里没生效呢，图片里大部分HS和SS的接口都已经屏蔽掉了

感谢。我已经搞定了。

**Comment by Android-AwesomeRoy** [comment]
> > 具体哪里没生效呢，图片里大部分HS和SS的接口都已经屏蔽掉了
> 
> 感谢。我已经搞定了。

请问如何搞定的？我也按照映射表重新配置了USBPorts.kext，按照README上的要求替换了文件，但是没有生效。
<img width="834" alt="image" src="https://user-images.githubusercontent.com/19187129/98447576-ddff3880-2160-11eb-889f-ee82344c3fe6.png">
