### ISSUE TITLE
老兄能抽空升级一下吗

### ISSUE THREAD

**Issue by recmess** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#10]
一直在用你的版本，显示还是5700xt，自己再小改改，稳定运行到现在了。

**Comment by imEgo** [comment]
好的这几天更新一下 主要我自己一直在用10.16，功能都正常没有太大必要更新

**Comment by imEgo** [comment]
> 一直在用你的版本，显示还是5700xt，自己再小改改，稳定运行到现在了。

均已更新至最新版本
