### ISSUE TITLE
请问你的 BIOS 里面设置主显卡是用板载还是外接的？

### ISSUE THREAD

**Issue by huijiewei** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#2]
我设置为主显卡用外接感觉有点卡

**Comment by imEgo** [comment]
主显卡是独立显卡，核显开启同时要使用最新的config里的配置将核显设置为无输出接口的，不然启动会在苹果Logo界面卡很久，不知道你的独显是什么型号

**Comment by huijiewei** [comment]
我用的独显是5500XT，核显注入ID和你的一样，都是只做加速。只是BIOS里面的设置就比较迷了。设置为PCI-E就有点卡。

**Comment by imEgo** [comment]
可以试试注入Framebuffer，注入后需要重建缓存，因为我是5700XT参数没办法测试，可以参考这个帖子的SSDT注入的方式，dAGPM这一步是不需要的，只做1 2 4就可以了
https://www.tonymacx86.com/threads/amd-radeon-performance-enhanced-ssdt.296555/

**Comment by huijiewei** [comment]
> https://www.tonymacx86.com/threads/amd-radeon-performance-enhanced-ssdt.296555/

感谢，我去试试

**Comment by huijiewei** [comment]
> 可以试试注入Framebuffer，注入后需要重建缓存，因为我是5700XT参数没办法测试，可以参考这个帖子的SSDT注入的方式，dAGPM这一步是不需要的，只做1 2 4就可以了
> https://www.tonymacx86.com/threads/amd-radeon-performance-enhanced-ssdt.296555/

我按照这个帖子做了。跑分从 2W8 到了 4W1，看来效果还是相当明显的

**Comment by imEgo** [comment]
如果不是公版显卡可以按照git里resources GPU里的方法定制下PP_PhmSoftPowerPlayTable

**Comment by huijiewei** [comment]
> 如果不是公版显卡可以按照git里resources GPU里的方法定制下PP_PhmSoftPowerPlayTable

公版是什么意思，我的是 华擎（ASRock）Radeon RX 5500XT Challenger D 8G。不知道是不是公版

**Comment by huijiewei** [comment]
感谢你的回复，我现在搞定了显卡的风扇和注入，一切完美。41632 Metal Score，39026 OpenCL Score
