### ISSUE TITLE
有几个疑问，请教一下！

### ISSUE THREAD

**Issue by recmess** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#3]
非常感谢提供的EFI，已成功用上，有几点疑问还想请教一下：
1、我的cPU是i7 9700k，如何才能显示正确？
2、我的显卡是蓝宝石 5700XT 8G，是否还要定制优化？
3、为了方便WINDOWS,我还是用主板自带的无线网卡和蓝牙，没有DW1560 。mac下用的是USB无线，是否可以直接把Brcm开头的kext删除？

**Comment by imEgo** [comment]
1. 删除config里CPU下面的Type即可
2. 最好根据自己显卡的配置定制
3. 可以，airport也一起删除

**Comment by recmess** [comment]
我把cpu/type 都删除了，还重建了缓存，还是显示i9,是否还有其它地方要修改？

**Comment by imEgo** [comment]
> 我把cpu/type 都删除了，还重建了缓存，还是显示i9,是否还有其它地方要修改？

那就把CPU - Type 改成0x0705 就会识别成i7了

**Comment by recmess** [comment]
谢谢
