### ISSUE TITLE
igfxfw

### ISSUE THREAD

**Issue by Kerrnel** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#4]
You have igxfw=2 - probably mean igfxfw=2 (untested)

**Comment by imEgo** [comment]
> You have igxfw=2 - probably mean igfxfw=2 (untested)

Just checked, It's "igfxfw", no typo in the config.plist I think

**Comment by Kerrnel** [comment]
Agreed after looking here. Sorry for the noise

**Comment by Kerrnel** [comment]
Agreed after looking here. Sorry for the noise
