### ISSUE TITLE
突然黑屏

### ISSUE THREAD

**Issue by recmess** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#5]
我的配置：
mac 10.15.5 
ASRock Z390m-ITX/ac
i7-9700k
蓝宝石 5700xt 白金 8g
32g内存
海康 1t NVMe ssd +4t 机械
comfast usb无线
用的是最新EFI，总共出现过3次，显示器是DP接口，突然一下黑屏，只能重启电脑。请问要怎样排查？谢谢

**Comment by imEgo** [comment]
> 我的配置：
> mac 10.15.5
> ASRock Z390m-ITX/ac
> i7-9700k
> 蓝宝石 5700xt 白金 8g
> 32g内存
> 海康 1t NVMe ssd +4t 机械
> comfast usb无线
> 用的是最新EFI，总共出现过3次，显示器是DP接口，突然一下黑屏，只能重启电脑。请问要怎样排查？谢谢

RadeonBoost.kext有加么，加了的话这个去掉试试，这个是针对我用的XFX海外版参数设置的

**Comment by recmess** [comment]
好的，我去掉试试，这个问题并不常见，接下来几天我观察一下。谢谢。

**Comment by imEgo** [comment]
> 好的，我去掉试试，这个问题并不常见，接下来几天我观察一下。谢谢。

应该是这个原因，因为我这个显卡GPU核心频率比标准版高了50MHz，并且我将内存频率超到了1900MHz，加之风扇转速不一样，是有一定几率会导致黑屏的；你可以根据自己显卡的参数按照Resources/GPU下的文档修改RadeonBoost.kext的PP_PhmSoftPowerPlayTable
注：删除或是修改了RadeonBoost.kext后要用Hackintools重建下缓存，不然一定几率会延用之前配置

**Comment by recmess** [comment]
导出了bios，其它还不会弄，目前把RadeonBoost.kext删除了，重建了缓存，几天下来没有黑屏，跑了分，以前是6-7万分，现在只有4万分左右。

**Comment by imEgo** [comment]
> 导出了bios，其它还不会弄，目前把RadeonBoost.kext删除了，重建了缓存，几天下来没有黑屏，跑了分，以前是6-7万分，现在只有4万分左右。

那你可以先把RadeonBoost.kext里的PP_PhmSoftPowerPlayTable删掉，只注入FBname和EFI就好了跑分可以恢复
倒入自己的参数其实就是用MorePowerTool打开显卡BIOS然后将各个值填入那个Excel里，然后将Excel里的output里的值复制出来用替换RadeonBoost.kext的PP_PhmSoftPowerPlayTable进行注入，需要注意的就是内存频率那里MorePowerTool的值是一半要乘2

**Comment by recmess** [comment]
按照你的方法，参考MorePowerTool里面的值，填入的Excel表里，并用output数值替换了PP_PhmSoftPowerPlayTable字段数值，拷入驱动后再重建缓存，目前一切正常，opencl跑分也恢复到了6.6万。观察几天，是否稳定。再次表示感谢！
