### ISSUE TITLE
DW1560网卡怎么装的？

### ISSUE THREAD

**Issue by dec2hex** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#6]
看你配置M.2接口装了个512GB 的ssd，那DW1560在这块板上你是怎么装的？天线怎么接的？

**Comment by imEgo** [comment]
> 看你配置M.2接口装了个512GB 的ssd，那DW1560在这块板上你是怎么装的？天线怎么接的？

主板本身不是有一个2天线的无线网卡么，把那个屏蔽罩拆开就能装一个NGFF的无线网卡
