### ISSUE TITLE
6/20 EFI 移除RadeonBoost后在哪定制显卡参数？

### ISSUE THREAD

**Issue by recmess** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#7]
谢谢指教！上一版很稳定啊。

**Comment by imEgo** [comment]
因为RadeonBoost是按照我使用的显卡型号定制的，所以移除了。定制教程按照[此链接](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh/blob/master/Resources/GPU/README.md)就好了，如果你定制好了直接放到kexts/Other就好
