### ISSUE TITLE
9700KF RX5700 公版，iMac19，1, Catalina 19G2021 无法硬解

### ISSUE THREAD

**Issue by aisyun** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#8]
9700KF RX5700 公版，iMac19，1, Catalina 19G2021 无法硬解。VDA 解码器解码失败

**Comment by imEgo** [comment]
说明有写“无核显配置建议更换机型为MacPro7,1自行适配”，现在的配置主要针对有核显的；或者可以试试启动命令行里加上```shikigva=160 shiki-id=Mac-7BA5B2D9E42DDD94```，WEG的FAQ里看到的不清楚有没有用

**Comment by aisyun** [comment]
改成MacPro 7,1，关于电脑信息显示to be OEM ， CPU传感器失效，cpu温度不显示。还有开机有错误代码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ego <notifications@github.com&gt;
发送时间: 2020年8月24日 13:25
收件人: imEgo/ASRock-Z390m-ITX-ac-Hackintosh <ASRock-Z390m-ITX-ac-Hackintosh@noreply.github.com&gt;
抄送: aisyun <81607316@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[imEgo/ASRock-Z390m-ITX-ac-Hackintosh] 9700KF RX5700 公版，iMac19，1, Catalina 19G2021 无法硬解 (#8)





 
说明有写“无核显配置建议更换机型为MacPro7,1自行适配”，现在的配置主要针对有核显的；或者可以试试启动命令行里加上shikigva=160 shiki-id=Mac-7BA5B2D9E42DDD94，WEG的FAQ里看到的不清楚有没有用

**Comment by imEgo** [comment]
可能因为我的OpenCore配置用了完整的SMBIOS配置，漏改的可能性会高一点，PlatformInfo整个替换成下面的精简版，或者先用Clover搞一个能启动的版本，然后再迁到OpenCore
```
<key>PlatformInfo</key>
<dict>
    <key>Automatic</key>
    <true/>
    <key>Generic</key>
    <dict>
        <key>AdviseWindows</key>
        <false/>
        <key>MLB</key>
        <string>F5K047501GUK3F7A8</string>
        <key>ROM</key>
        <data>kLdDBr7m</data>
        <key>SpoofVendor</key>
        <true/>
        <key>SystemProductName</key>
        <string>MacPro7,1</string>
        <key>SystemSerialNumber</key>
        <string>F5KDQAZCP7QM</string>
        <key>SystemUUID</key>
        <string>6B5680F7-B2BA-450A-8C7D-D8D26906BEE6</string>
    </dict>
    <key>UpdateDataHub</key>
    <true/>
    <key>UpdateNVRAM</key>
    <true/>
    <key>UpdateSMBIOS</key>
    <true/>
    <key>UpdateSMBIOSMode</key>
    <string>Create</string>
</dict>
```
