### ISSUE TITLE
你好！请问如何解决？

### ISSUE THREAD

**Issue by tomson6911** [imEgo/ASRock-Z390m-ITX-ac-Hackintosh#9]
你好！我的配置基本和你的一样，找了若干EFI，你的最合适，非常感谢！！！但有个问题：
刚启动时出现OCS: Failed to parse data field as value with type data and <Rep lacebyyourROM> contents, context <ROM> !
停顿几秒后可以继续启动正常进入系统，请问怎么解决？

**Comment by awesomeroy-cloud** [comment]
> 你好！我的配置基本和你的一样，找了若干EFI，你的最合适，非常感谢！！！但有个问题：
> 刚启动时出现OCS: Failed to parse data field as value with type data and contents, context !
> 停顿几秒后可以继续启动正常进入系统，请问怎么解决？

我刚用他的配置信息时也遇到了这个问题，原因是plist有一个关键字是填了不规范的值，你下次开机注意观察给你提示的关键字，然后去plist里找一下对应的key和value，修改成规范的就行了。

**Comment by tomson6911** [comment]
> > 你好！我的配置基本和你的一样，找了若干EFI，你的最合适，非常感谢！！！但有个问题：
> > 刚启动时出现OCS: Failed to parse data field as value with type data and contents, context !
> > 停顿几秒后可以继续启动正常进入系统，请问怎么解决？
> 
> 我刚用他的配置信息时也遇到了这个问题，原因是plist有一个关键字是填了不规范的值，你下次开机注意观察给你提示的关键字，然后去plist里找一下对应的key和value，修改成规范的就行了。

谢谢！待会试试看！

**Comment by imEgo** [comment]
是不是苹果三码MLB、SerialNumber这些我留空的没有换成自己的？config.plist里搜一下关键字!!!Replace-by-your-，然后参考[README](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E8%A1%A5%E5%85%A8smbios)里的说明补全上去

**Comment by tomson6911** [comment]
> 是不是苹果三码MLB、SerialNumber这些我留空的没有换成自己的？config.plist里搜一下关键字!!!Replace-by-your-，然后参考[README](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E8%A1%A5%E5%85%A8smbios)里的说明补全上去

是的 没有换 本想这个问题解决了再换 多谢了 有问题再联系你！

**Comment by tomson6911** [comment]
> 是不是苹果三码MLB、SerialNumber这些我留空的没有换成自己的？config.plist里搜一下关键字!!!Replace-by-your-，然后参考[README](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E8%A1%A5%E5%85%A8smbios)里的说明补全上去

又出现了这两种问题：
OCS: No schema for CustomMemory at 1 index, context <PlatformInfo> !
OCS: NO schema for ForceResolution at 3 index, context <0utput> !
 调整PlatformInfo参数也没解决！

能给个邮箱吗？把config文件发给你 帮给调一下？

**Comment by imEgo** [comment]
> > 是不是苹果三码MLB、SerialNumber这些我留空的没有换成自己的？config.plist里搜一下关键字!!!Replace-by-your-，然后参考[README](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E8%A1%A5%E5%85%A8smbios)里的说明补全上去
> 
> 又出现了这两种问题：
> OCS: No schema for CustomMemory at 1 index, context !
> OCS: NO schema for ForceResolution at 3 index, context <0utput> !
> 调整PlatformInfo参数也没解决！
> 
> 能给个邮箱吗？把config文件发给你 帮给调一下？

这个是昨天更新的0.6.3 OpenCore新加的字段，0.6.2肯定会报错，你把OpenCore也更新到git最新的就好了，OC基本每个版本都会增加几个字段，config一定要配合git的其他资源一起更新，对更新内容不清楚可以看下[更新记录](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh/blob/master/CHANGELOG.md)或是Commit history

**Comment by tomson6911** [comment]
> > > 是不是苹果三码MLB、SerialNumber这些我留空的没有换成自己的？config.plist里搜一下关键字!!!Replace-by-your-，然后参考[README](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E8%A1%A5%E5%85%A8smbios)里的说明补全上去
> > 
> > 
> > 又出现了这两种问题：
> > OCS: No schema for CustomMemory at 1 index, context !
> > OCS: NO schema for ForceResolution at 3 index, context <0utput> !
> > 调整PlatformInfo参数也没解决！
> > 能给个邮箱吗？把config文件发给你 帮给调一下？
> 
> 这个是昨天更新的0.6.3 OpenCore新加的字段，0.6.2肯定会报错，你把OpenCore也更新到git最新的就好了，OC基本每个版本都会增加几个字段，config一定要配合git的其他资源一起更新，对更新内容不清楚可以看下[更新记录](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh/blob/master/CHANGELOG.md)或是Commit history

多谢啦！刚开始玩黑苹果 小菜一个 多谢指教！

**Comment by tomson6911** [comment]
@imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。

**Comment by awesomeroy-cloud** [comment]
> @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。

我还在用0.62，type-C 用不了。还不知道怎么解决。

**Comment by imEgo** [comment]
> @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。

> > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> 
> 我还在用0.62，type-C 用不了。还不知道怎么解决。

首先确认机型使用的是iMac19,1，然后参考[定制USB接口](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E5%AE%9A%E5%88%B6usb%E6%8E%A5%E5%8F%A3)重新定制下试试，我这边都是正常的

**Comment by awesomeroy-cloud** [comment]
> > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> 
> > > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> > 
> > 
> > 我还在用0.62，type-C 用不了。还不知道怎么解决。
> 
> 首先确认机型使用的是iMac19,1，然后参考[定制USB接口](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E5%AE%9A%E5%88%B6usb%E6%8E%A5%E5%8F%A3)重新定制下试试，我这边都是正常的

好的，我正在调试。今晚更新您提供的最新版时，出现了禁止符号，目前回退到了上一个版本，还发现了一个新的问题，我买了一个音响，后面版的所有音频插口都无法使用，以前的桌面式麦克风也不能用了。

**Comment by imEgo** [comment]
> > > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> > 
> > 
> > > > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> > > 
> > > 
> > > 我还在用0.62，type-C 用不了。还不知道怎么解决。
> > 
> > 
> > 首先确认机型使用的是iMac19,1，然后参考[定制USB接口](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E5%AE%9A%E5%88%B6usb%E6%8E%A5%E5%8F%A3)重新定制下试试，我这边都是正常的
> 
> 好的，我正在调试。今晚更新您提供的最新版时，出现了禁止符号，目前回退到了上一个版本，还发现了一个新的问题，我买了一个音响，后面版的所有音频插口都无法使用，以前的桌面式麦克风也不能用了。

看样子是很多驱动没有正确加载，先重建下缓存，然后用Hackintool里的内核扩展看下Lilu和AppleALC有没有正确加载。ALC注入ID要用22，这个是我针对这个主板专门修改过的。如果EFI没有自己改过东西，可以尝试下重置NVRAM，然后重建下缓存，能解决很多疑难杂症。。。

**Comment by Android-AwesomeRoy** [comment]
> > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> 
> > > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> > 
> > 
> > 我还在用0.62，type-C 用不了。还不知道怎么解决。
> 
> 首先确认机型使用的是iMac19,1，然后参考[定制USB接口](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E5%AE%9A%E5%88%B6usb%E6%8E%A5%E5%8F%A3)重新定制下试试，我这边都是正常的

关于这个问题我在已经close的issue下发送了。https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh/issues/1#issuecomment-723471460

**Comment by awesomeroy-cloud** [comment]
> > > > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> > > 
> > > 
> > > > > @imEgo 非常感谢！昨天的问题都解决了。但发现一个新的问题：前面板的2个USB口和后面的USB+TYPE-C口都用不了，以前老版的都没问题。
> > > > 
> > > > 
> > > > 我还在用0.62，type-C 用不了。还不知道怎么解决。
> > > 
> > > 
> > > 首先确认机型使用的是iMac19,1，然后参考[定制USB接口](https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh#%E5%AE%9A%E5%88%B6usb%E6%8E%A5%E5%8F%A3)重新定制下试试，我这边都是正常的
> > 
> > 
> > 好的，我正在调试。今晚更新您提供的最新版时，出现了禁止符号，目前回退到了上一个版本，还发现了一个新的问题，我买了一个音响，后面版的所有音频插口都无法使用，以前的桌面式麦克风也不能用了。
> 
> 看样子是很多驱动没有正确加载，先重建下缓存，然后用Hackintool里的内核扩展看下Lilu和AppleALC有没有正确加载。ALC注入ID要用22，这个是我针对这个主板专门修改过的。如果EFI没有自己改过东西，可以尝试下重置NVRAM，然后重建下缓存，能解决很多疑难杂症。。。

后面版音频插口问题，重建缓存和reset NVRAM都无效。
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/19187129/98448846-1d7e5280-216a-11eb-84b7-3ba057e962ce.png">
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/19187129/98448917-8c5bab80-216a-11eb-8758-81ce026ee8b9.png">

**Comment by imEgo** [comment]
@Android-AwesomeRoy 你主板是Z390 Phantom Gaming-ITX/ac吧，USB那个图里有TB3，声卡图里是ALC1220，虽然都是华擎的Z390 ITX，但是这两个板子很多硬件是不一样的，首先我这个板子是没有TB3的USB接口映射跟你的应该不一样，其次这个声卡是ALC892，不能直接套用。。。

**Comment by awesomeroy-cloud** [comment]
> @Android-AwesomeRoy 你主板是Z390 Phantom Gaming-ITX/ac吧，USB那个图里有TB3，声卡图里是ALC1220，虽然都是华擎的Z390 ITX，但是这两个板子很多硬件是不一样的，首先我这个板子是没有TB3的USB接口映射跟你的应该不一样，其次这个声卡是ALC892，不能直接套用。。。

感谢提醒，我光到都是Z390itx了，还真没注意到Gaming

**Comment by tomson6911** [comment]
@imEgo 现在用的是核显+hdmi口，启动时或休眠后得重新插拔一次显示器才正常，并且显示器颜色偏色，如何解决？远景上也搜过了 都不行。

**Comment by imEgo** [comment]
> @imEgo 现在用的是核显+hdmi口，启动时或休眠后得重新插拔一次显示器才正常，并且显示器颜色偏色，如何解决？远景上也搜过了 都不行。

只有核显么？只有核显的话用igpu-only分支的config.plist的PciRoot(0x0)/Pci(0x2,0x0)下面的替换master分支config.plist里的所有值，最早我单核显的时候适配过framebuffer，HDMI和DP接口都是正常的
